// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.edu.hust.grpc.api.user;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_edu_hust_grpc_user_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_edu_hust_grpc_user_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_edu_hust_grpc_user_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_edu_hust_grpc_user_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022\025cn.edu.hust.grpc.us" +
      "er\"\033\n\013UserRequest\022\014\n\004name\030\001 \001(\t\":\n\014UserR" +
      "esponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\017\n\007ad" +
      "dress\030\003 \001(\t2_\n\013UserService\022P\n\005query\022\".cn" +
      ".edu.hust.grpc.user.UserRequest\032#.cn.edu" +
      ".hust.grpc.user.UserResponseB\035\n\031cn.edu.h" +
      "ust.grpc.api.userP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_edu_hust_grpc_user_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_edu_hust_grpc_user_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_edu_hust_grpc_user_UserRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_cn_edu_hust_grpc_user_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_edu_hust_grpc_user_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_edu_hust_grpc_user_UserResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
