// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package cn.edu.hust.grpc.api.user;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.edu.hust.grpc.user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
